name: Generate Release Build

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  PACKAGE_NAME: Rbxl2Poly 

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: |
            target/release/${{ env.PACKAGE_NAME }}
            USAGE.md
            LICENSE.txt